/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wordlePackage;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author malil6384
 */
public class wordleJFrame extends javax.swing.JFrame {

    /**
     * Creates new form wordleJFrame
     */
    public wordleJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuess = new javax.swing.JButton();
        txtGuess = new javax.swing.JTextField();
        btnRow1Char1 = new javax.swing.JButton();
        btnRow1Char2 = new javax.swing.JButton();
        btnRow1Char3 = new javax.swing.JButton();
        btnRow1Char4 = new javax.swing.JButton();
        btnRow1Char5 = new javax.swing.JButton();
        btnRow2Char1 = new javax.swing.JButton();
        btnRow2Char2 = new javax.swing.JButton();
        btnRow2Char3 = new javax.swing.JButton();
        btnRow2Char4 = new javax.swing.JButton();
        btnRow2Char5 = new javax.swing.JButton();
        btnRow3Char1 = new javax.swing.JButton();
        btnRow3Char2 = new javax.swing.JButton();
        btnRow3Char3 = new javax.swing.JButton();
        btnRow3Char4 = new javax.swing.JButton();
        btnRow3Char5 = new javax.swing.JButton();
        btnRow4Char1 = new javax.swing.JButton();
        btnRow4Char2 = new javax.swing.JButton();
        btnRow4Char3 = new javax.swing.JButton();
        btnRow4Char4 = new javax.swing.JButton();
        btnRow4Char5 = new javax.swing.JButton();
        btnRow5Char1 = new javax.swing.JButton();
        btnRow5Char2 = new javax.swing.JButton();
        btnRow5Char3 = new javax.swing.JButton();
        btnRow5Char4 = new javax.swing.JButton();
        btnRow5Char5 = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        txtInstructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        txtGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuessActionPerformed(evt);
            }
        });

        btnRow1Char1.setBackground(new java.awt.Color(255, 255, 255));
        btnRow1Char1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow1Char1ActionPerformed(evt);
            }
        });

        btnRow1Char2.setBackground(new java.awt.Color(255, 255, 255));
        btnRow1Char2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow1Char2ActionPerformed(evt);
            }
        });

        btnRow1Char3.setBackground(new java.awt.Color(255, 255, 255));
        btnRow1Char3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow1Char3ActionPerformed(evt);
            }
        });

        btnRow1Char4.setBackground(new java.awt.Color(255, 255, 255));
        btnRow1Char4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow1Char4ActionPerformed(evt);
            }
        });

        btnRow1Char5.setBackground(new java.awt.Color(255, 255, 255));
        btnRow1Char5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow1Char5ActionPerformed(evt);
            }
        });

        btnRow2Char1.setBackground(new java.awt.Color(255, 255, 255));
        btnRow2Char1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow2Char1ActionPerformed(evt);
            }
        });

        btnRow2Char2.setBackground(new java.awt.Color(255, 255, 255));
        btnRow2Char2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow2Char2ActionPerformed(evt);
            }
        });

        btnRow2Char3.setBackground(new java.awt.Color(255, 255, 255));
        btnRow2Char3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow2Char3ActionPerformed(evt);
            }
        });

        btnRow2Char4.setBackground(new java.awt.Color(255, 255, 255));
        btnRow2Char4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow2Char4ActionPerformed(evt);
            }
        });

        btnRow2Char5.setBackground(new java.awt.Color(255, 255, 255));
        btnRow2Char5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow2Char5ActionPerformed(evt);
            }
        });

        btnRow3Char1.setBackground(new java.awt.Color(255, 255, 255));
        btnRow3Char1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow3Char1ActionPerformed(evt);
            }
        });

        btnRow3Char2.setBackground(new java.awt.Color(255, 255, 255));
        btnRow3Char2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow3Char2ActionPerformed(evt);
            }
        });

        btnRow3Char3.setBackground(new java.awt.Color(255, 255, 255));
        btnRow3Char3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow3Char3ActionPerformed(evt);
            }
        });

        btnRow3Char4.setBackground(new java.awt.Color(255, 255, 255));
        btnRow3Char4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow3Char4ActionPerformed(evt);
            }
        });

        btnRow3Char5.setBackground(new java.awt.Color(255, 255, 255));
        btnRow3Char5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow3Char5ActionPerformed(evt);
            }
        });

        btnRow4Char1.setBackground(new java.awt.Color(255, 255, 255));
        btnRow4Char1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow4Char1ActionPerformed(evt);
            }
        });

        btnRow4Char2.setBackground(new java.awt.Color(255, 255, 255));
        btnRow4Char2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow4Char2ActionPerformed(evt);
            }
        });

        btnRow4Char3.setBackground(new java.awt.Color(255, 255, 255));
        btnRow4Char3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow4Char3ActionPerformed(evt);
            }
        });

        btnRow4Char4.setBackground(new java.awt.Color(255, 255, 255));
        btnRow4Char4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow4Char4ActionPerformed(evt);
            }
        });

        btnRow4Char5.setBackground(new java.awt.Color(255, 255, 255));
        btnRow4Char5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow4Char5ActionPerformed(evt);
            }
        });

        btnRow5Char1.setBackground(new java.awt.Color(255, 255, 255));
        btnRow5Char1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow5Char1ActionPerformed(evt);
            }
        });

        btnRow5Char2.setBackground(new java.awt.Color(255, 255, 255));
        btnRow5Char2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow5Char2ActionPerformed(evt);
            }
        });

        btnRow5Char3.setBackground(new java.awt.Color(255, 255, 255));
        btnRow5Char3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow5Char3ActionPerformed(evt);
            }
        });

        btnRow5Char4.setBackground(new java.awt.Color(255, 255, 255));
        btnRow5Char4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow5Char4ActionPerformed(evt);
            }
        });

        btnRow5Char5.setBackground(new java.awt.Color(255, 255, 255));
        btnRow5Char5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRow5Char5ActionPerformed(evt);
            }
        });

        txtTitle.setText("Wordle Project");

        txtInstructions.setText("Make sure the word you enter is exactly 5 characters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRow5Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow5Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow5Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow5Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow5Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRow4Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow4Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow4Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow4Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow4Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRow3Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow3Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow3Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow3Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow3Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuess))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRow2Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow2Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow2Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow2Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow2Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRow1Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow1Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow1Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow1Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRow1Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtInstructions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRow1Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRow1Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRow1Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRow1Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRow1Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRow2Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRow3Char1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Char2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRow4Char1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(btnRow4Char2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRow4Char3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow4Char4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow4Char5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRow5Char1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnRow5Char2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRow5Char3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRow5Char4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRow5Char5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInstructions)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuessActionPerformed

    private void btnRow1Char1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow1Char1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow1Char1ActionPerformed

    private void btnRow1Char2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow1Char2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow1Char2ActionPerformed

    private void btnRow1Char3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow1Char3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow1Char3ActionPerformed

    private void btnRow1Char4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow1Char4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow1Char4ActionPerformed

    private void btnRow1Char5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow1Char5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow1Char5ActionPerformed

    private void btnRow2Char1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow2Char1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow2Char1ActionPerformed

    private void btnRow2Char2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow2Char2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow2Char2ActionPerformed

    private void btnRow2Char3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow2Char3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow2Char3ActionPerformed

    private void btnRow2Char4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow2Char4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow2Char4ActionPerformed

    private void btnRow2Char5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow2Char5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow2Char5ActionPerformed

    private void btnRow3Char1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow3Char1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow3Char1ActionPerformed

    private void btnRow3Char2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow3Char2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow3Char2ActionPerformed

    private void btnRow3Char3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow3Char3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow3Char3ActionPerformed

    private void btnRow3Char4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow3Char4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow3Char4ActionPerformed

    private void btnRow3Char5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow3Char5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow3Char5ActionPerformed

    private void btnRow4Char1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow4Char1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow4Char1ActionPerformed

    private void btnRow4Char2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow4Char2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow4Char2ActionPerformed

    private void btnRow4Char3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow4Char3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow4Char3ActionPerformed

    private void btnRow4Char4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow4Char4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow4Char4ActionPerformed

    private void btnRow4Char5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow4Char5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow4Char5ActionPerformed

    private void btnRow5Char1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow5Char1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow5Char1ActionPerformed

    private void btnRow5Char2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow5Char2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow5Char2ActionPerformed

    private void btnRow5Char3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow5Char3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow5Char3ActionPerformed

    private void btnRow5Char4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow5Char4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow5Char4ActionPerformed

    private void btnRow5Char5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRow5Char5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRow5Char5ActionPerformed

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        switch (counter) {
            case 0:
                play(btnRow1Char1, btnRow1Char2, btnRow1Char3, btnRow1Char4, btnRow1Char5, txtGuess.getText());
                break;
            case 1:
                play(btnRow2Char1, btnRow2Char2, btnRow2Char3, btnRow2Char4, btnRow2Char5, txtGuess.getText());
                break;
            case 2:
                play(btnRow3Char1, btnRow3Char2, btnRow3Char3, btnRow3Char4, btnRow3Char5, txtGuess.getText());
                break;
            case 3:
                play(btnRow4Char1, btnRow4Char2, btnRow4Char3, btnRow4Char4, btnRow4Char5, txtGuess.getText());
                break;
            case 4:
                play(btnRow5Char1, btnRow5Char2, btnRow5Char3, btnRow5Char4, btnRow5Char5, txtGuess.getText());
                break;
            default:
                txtTitle.setText("Out of turns!");
                break;
        }
    }//GEN-LAST:event_btnGuessActionPerformed

    //Variables
    Wordle word = new Wordle();
    int counter = 0;
    boolean winner = false;
    
    
    //Method to control playing the game
    public void play(JButton btn1, JButton btn2, JButton btn3, JButton btn4, JButton btn5, String str){
        //Uses class to get array values
        int[][] array = word.guesser(txtGuess.getText());
        //Setting new colors
        Color clr1 = new Color(array[0][0], array[0][1], array[0][2]);
        Color clr2 = new Color(array[1][0], array[1][1], array[1][2]);
        Color clr3 = new Color(array[2][0], array[2][1], array[2][2]);
        Color clr4 = new Color(array[3][0], array[3][1], array[3][2]);
        Color clr5 = new Color(array[4][0], array[4][1], array[4][2]);
        //Giving array rgb values to buttons to se the color
        btn1.setBackground(clr1);
        btn2.setBackground(clr2);
        btn3.setBackground(clr3);
        btn4.setBackground(clr4);
        btn5.setBackground(clr5);
        //Settign text for buttons
        btn1.setText(str.substring(0,1));
        btn2.setText(str.substring(1,2));
        btn3.setText(str.substring(2,3));
        btn4.setText(str.substring(3,4));
        btn5.setText(str.substring(4));
        //Increase counter variable
        counter++;
        //Reset txt box
        txtGuess.setText("");
    }
    
   
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wordleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wordleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wordleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wordleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wordleJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnRow1Char1;
    private javax.swing.JButton btnRow1Char2;
    private javax.swing.JButton btnRow1Char3;
    private javax.swing.JButton btnRow1Char4;
    private javax.swing.JButton btnRow1Char5;
    private javax.swing.JButton btnRow2Char1;
    private javax.swing.JButton btnRow2Char2;
    private javax.swing.JButton btnRow2Char3;
    private javax.swing.JButton btnRow2Char4;
    private javax.swing.JButton btnRow2Char5;
    private javax.swing.JButton btnRow3Char1;
    private javax.swing.JButton btnRow3Char2;
    private javax.swing.JButton btnRow3Char3;
    private javax.swing.JButton btnRow3Char4;
    private javax.swing.JButton btnRow3Char5;
    private javax.swing.JButton btnRow4Char1;
    private javax.swing.JButton btnRow4Char2;
    private javax.swing.JButton btnRow4Char3;
    private javax.swing.JButton btnRow4Char4;
    private javax.swing.JButton btnRow4Char5;
    private javax.swing.JButton btnRow5Char1;
    private javax.swing.JButton btnRow5Char2;
    private javax.swing.JButton btnRow5Char3;
    private javax.swing.JButton btnRow5Char4;
    private javax.swing.JButton btnRow5Char5;
    private javax.swing.JTextField txtGuess;
    private javax.swing.JLabel txtInstructions;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
